### ISSUE TITLE
Add Badges to README.md

### ISSUE THREAD

**Issue by honmanyau** [honmanyau/ising#2]
**This Issue is strictly meant for beginners! Please indicate that you would like to try tackling this issue and ask questions if you are unsure.**

**In addition, please do NOT submit a pull request if this is not assigned to you—otherwise your PR will be marked with an invalid tag.**

## Description

Add the following badges to README.md **in markdown format**: NPM version, vulnerabilities, license.

## Instructions

Each of the badges should have an alt text and link as follows:

| Type | Alt Text | LInk |
|------|---------|-----|
| NPM Version | NPM Version | https://www.npmjs.com/package/ising |
| Vulnerabilities | Known Vulnerabilities | https://snyk.io/test/npm/ising |
| License | License: MIT | https://github.com/honmanyau/ising/blob/master/LICENSE.md |

Useful links:

* https://shields.io
* https://snyk.io/docs/badges
* [Contributor's guide](https://github.com/honmanyau/ising/blob/master/CONTRIBUTING.md)

## Remarks

In case it's not already clear, **this Issue is strictly meant for beginners**!

**Comment by honmanyau** [comment]
This issue is temporarily closed until PR #3 is resolved.

**Comment by honmanyau** [comment]
This issue has been reopened since the related PRs are not stale and closed. Please read the instructions in the first comment before submitting a PR; otherwise your PR will be tagged invalid.

**Comment by geekyrajshri** [comment]
@honmanyau I would like to take this issue.
<img width="640" alt="screen shot 2018-10-10 at 11 30 33 am" src="https://user-images.githubusercontent.com/8193580/46716118-593f4900-cc80-11e8-8edb-6756006e122b.png">
Is this something which you want?

**Comment by honmanyau** [comment]
@geekyrajshri Yup! Those are what I'm looking for but just the three mentioned in the table with those specific links! If you are happy with that, go for it! :)

**Comment by honmanyau** [comment]
This issue has been closed by #6! ☀️
